algoritmo "semnome"
var
numero : inteiro
num : inteiro
resp: caracter

inicio
numero :=1
num := num
resp:= "S"
enquanto (resp = "s") faca
         escreva("Qual número você quer pra fazer a tabuaba: ")
         Leia(num)
enquanto (numero<=10) faca
         escreval (numero," x ", num, " = ", num*numero)
         numero:= numero +1

Fimenquanto
      numero:=1
      Escreva("Você quer fazer outro número [S/N]?")
      Leia(resp)
Fimenquanto
fimalgoritmo